version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    environment:
      - NODE_ENV=development