[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name   tail
    Path   /var/lib/docker/containers/*/*-json.log
    Parser docker
    Tag    clouding.*

[FILTER]
    Name   modify
    Match  clouding.*
    Add    app clouding-lab

[OUTPUT]
    Name   loki
    Match  clouding.*
    Host   loki
    Port   3100
    Labels job=fluent-bit,app=clouding-lab