apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clouding-lab
  namespace: clouding-lab
spec:
  rules:
    - host: aws.clouding.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
